// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeoUMJKopQol4p0PhkZ7k4dQGGSO4BLvg',
    appId: '1:837952930666:web:008231005f138a6f66db13',
    messagingSenderId: '837952930666',
    projectId: 'mentalhealth-1cd10',
    authDomain: 'mentalhealth-1cd10.firebaseapp.com',
    storageBucket: 'mentalhealth-1cd10.appspot.com',
    measurementId: 'G-BBQWP3HWJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2mIXs67CVUIrAXstng_I2c7FITm_QcqI',
    appId: '1:837952930666:android:ff85645b803e93f866db13',
    messagingSenderId: '837952930666',
    projectId: 'mentalhealth-1cd10',
    storageBucket: 'mentalhealth-1cd10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsnBh8OVYw81NluNY3qtpBuM9W_Z-Zcro',
    appId: '1:837952930666:ios:34d60bb275a3db7066db13',
    messagingSenderId: '837952930666',
    projectId: 'mentalhealth-1cd10',
    storageBucket: 'mentalhealth-1cd10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsnBh8OVYw81NluNY3qtpBuM9W_Z-Zcro',
    appId: '1:837952930666:ios:34d60bb275a3db7066db13',
    messagingSenderId: '837952930666',
    projectId: 'mentalhealth-1cd10',
    storageBucket: 'mentalhealth-1cd10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeoUMJKopQol4p0PhkZ7k4dQGGSO4BLvg',
    appId: '1:837952930666:web:ba9800f3a25ec20166db13',
    messagingSenderId: '837952930666',
    projectId: 'mentalhealth-1cd10',
    authDomain: 'mentalhealth-1cd10.firebaseapp.com',
    storageBucket: 'mentalhealth-1cd10.appspot.com',
    measurementId: 'G-Q5893X2VH7',
  );
}
